### ISSUE TITLE
TODOs for updating the model

### ISSUE THREAD

**Issue by michaelchughes** [tufts-ml/covid19-forecasting#11]
## Personalizing risk probabilities

@rathp Want to update PatientTrajectory.py to include "age" or other covariates.

Look over research literature, see if you can find age-specific or condition-specific estimates of:
* who is presenting at hospital with symptoms
* who is progressing to each stage
* how long they are staying at each stage (e.g. is recovery longer for older patients?)

## Improving the model

@hzhzhzhzhzhzhz Want to make the markov model more realistic.

Current:  GeneralWard + decline > ICU  + decline > Vent + recover > LEAVE MODEL

Ideal: General + decline > ICU  + decline > Vent + recover > ICU + recover > General + recover

First steps:

What (if anything) would we change the markov model spec here:
https://github.com/tufts-ml/covid19-forecasting/blob/master/params_simple_example.json
or the code in PatientTrajectory.py

**Comment by rathp** [comment]
## Link to Age Related Demographics Literature Survey 
[https://docs.google.com/document/d/1a1lKY4ElVh7bh9RpD7TL3kzhfZGn13ELtsZRlUYCNsM/edit](url)

**Comment by michaelchughes** [comment]
@hzhzhzhzhzhzhz progress on making model more realistic in the state progression?

**Comment by hzhz2020** [comment]
> @hzhzhzhzhzhzhz progress on making model more realistic in the state progression?

making the modification and doing some sanity check, should be able to discuss with you soon.

**Comment by michaelchughes** [comment]
See PR #21 and PR #22 that address this issue. Will move further discussion there!
