### ISSUE TITLE
TODO revise PatientTrajectory class to include admit_type : "referral" or "new"

### ISSUE THREAD

**Issue by michaelchughes** [tufts-ml/covid19-forecasting#12]
## Summary 

This change came from conversation with TMC stakeholders Tues 04/07

## Background

Tufts Medical is part of a big hospital system called wellforce

Currently, numbers at TMC are lower than other area hospitals. 

Expectation is that this will change as other area hospitals "fill up" and refer patients to TMC

TMC will then have a "mixture" of two types of patients:
* Those who come in directly from home (what our model already assumed, will call these admit_type="new")
* Those who come in from other hospitals, having already been hospitalized there (admit_type="referral")

We want to quickly revise the model so that can specify progression probabilities by admit_type (collaborators speculate that referred patients might have different demographic characteristics and different chances of recovering). 

## Proposed changes to params.json

For each essential parameter (e.g. proba_Recovering_given_{state}, and pmf_timesteps_{status}_{state}), we now accept TWO forms of probability:

* Form 1: just value (as before)

"proba_Recovering_given_InICU": 0.5

* Form 2: a dict of probability values keyed by admit_type

"proba_Recovering_given_InICU": {"new": 0.5, "referral: 0.1}

Key idea for expansion: we have a predefined order of patient attributes (e.g. ['age', 'admit_type', 'has_diabetes', 'has_heart_disease'])
When defining parameters for a patient, we try each key in order.  

## Proposed changes to PatientTrajectory.py

Add attribute: "admit_type"

Inside simulate trajectory, sample from the most specific attribute-driven distribution you can

**Comment by gvisani** [comment]
Do we have to predict how many patients will be referred to TMC? Has TMC given guidance on this? I suspect it is harder than modeling the incoming of "new" patients

**Comment by michaelchughes** [comment]
Yes, we've been told that they'll give us two "inputs':
* num "new" patients per day
* num "referral" patients per day
We'll see what happens in practice. Definitely agree harder to model/guess how that works.

**Comment by michaelchughes** [comment]
OK for now we've avoided having separate transition dynamics for these two types.

Instead, we're just going with simple solution of adding referrals directly into ICU, and having them transition like any other patient. Simple and effective.
