### ISSUE TITLE
County data

### ISSUE THREAD

**Issue by panlybero** [tufts-ml/covid19-forecasting#14]
Look at NYT dataset for county level data.
Interested in:
- Chime parameters
- Data to evaluate our models (hospitalizations, infections, deaths, icus etc)

**Comment by michaelchughes** [comment]
Yes! Would be great to have as fine-grained as possible for each day that we can between say 03/15/20 and present

Thanks @panlybero

**Comment by michaelchughes** [comment]
Thanks again for this @panlybero 

Seems like we have the county-level data for now in CSV files in covid19-forecasting/nyt_data/counties/

Will close this issue for now, lemme know if there's other features this needs via a separate issue
